### ISSUE TITLE
Data Modes support

### ISSUE THREAD

**Issue by rafael2k** [xssfox/freedv-tnc#4]
Do you have plans to support DATAC1, DATAC2 and DATAC3 modes?

They are described here:
https://github.com/drowe67/codec2/blob/master/README_data.md

**Comment by xssfox** [comment]
certainly! I hadn't seen that those modems became ready so I'll have to look into incorporating them. It shouldn't be hard (famous last words) but I'm travelling soon so might not get a chance to look at it the short term.

**Comment by drowe67** [comment]
Theses modes (and the raw data API) are under active development so I'd suggest holding off for a while until the physical layer is stable and tested.

**Comment by rafael2k** [comment]
Right, thanks David! 
Let us know when you consider it stable.

**Comment by M0LTE** [comment]
@drowe67 @rafael2k did this ever happen? Super interested!

**Comment by rafael2k** [comment]
I have a feeling it is! FreeDATA uses them:
https://github.com/DJ2LS/FreeDATA

**Comment by M0LTE** [comment]
I'd love to see these modes incorporated @xssfox - let me know if I can sponsor the work.

**Comment by xssfox** [comment]
I haven't looked at this project for awhile since I thought FreeDATA was a bit better for a solution but if there's still a need for freedv-tnc I could take a look. I suspect codec2 library has changed a bit so it might require a bit of investigation. The nice new modems also might allow me to remove some hacks I made which lowered overall speed

**Comment by M0LTE** [comment]
Sounds amazing. I feel there is a definite use for a Codec2 modem with a KISS interface. Use case here would be as a drop-in replacement for 300 baud Bell tones for HF links between BPQ instances.

**Comment by M0LTE** [comment]
@xssfox I am happy to sponsor this work if it helps.

**Comment by xssfox** [comment]
Thanks @M0LTE, It is however more of a finding time problem. Last Wednesday I did get a test setup running again and compiled freedv-tnc with the latest codec2 build. My next steps is making sure that works as I was running into some issues with the existing 700D/E modems - but it might of just been my test setup.

Once I confirm 700D/E are working properly again I'll have a look at the new data modes. Looking at `freedv_data_raw_rx.c` (and from memory) I don't think there will be a huge amount of changes required to make it work as I tried to write this in a way that will work with any future modes.


I need to double check that modem initialisation hasn't changed, work out how to determine `max_packet_size`, update the enum for modem types and fingers crossed it should work 😅 


I'm not familiar with BPQ - have you tested it using existing 700d/e freedv-tnc ? I'm not sure I'll have a way to test this.

**Comment by M0LTE** [comment]
Two of us attempted to test it a week ago but the propagation let us down.

Latest beta of QtTermTCP can connect directly to a TCP KISS modem and can also listen for incoming KISS connections- this would make an ideal test bed without the complexity of BPQ. Official builds are for i386 only (yes, I know) but I have builds for amd64 if you need. Shout up.

**Comment by M0LTE** [comment]
In fact here is the link.

https://github.com/M0LTE/QtTermTCP-builds

**Comment by M0LTE** [comment]
@xssfox Any joy finding the time to make this happen?

**Comment by xssfox** [comment]
Here's where I've gotten to - https://github.com/xssfox/freedv-tnc/tree/WIP I resolved a bunch of memory issues but in debugging I made quite a mess of the code

I've got 700D to work again. DATAC* modes make noise however something is wrong as it can demodulate them and `freedv_data_raw_rx` doesn't like them.

**Comment by xssfox** [comment]
@M0LTE I had another look at this and figured out the problem - I didn't know that the rawdatarx api calls for the new data modes checked a crc. We were calculating our own crc16 which worked fine for our purposes however freedv was ignore our packets because they didn't match its expectations. I switched to using the crc checksum inside freedv and it seems work.

**Comment by xssfox** [comment]
After reconfiguring scrambling I was able to get the following working
DATAC0, DATAC1, DATAC3, DATAC4, FSK_LDPC 

These did not work
DATAC13 (audio, no decode), 700E (no audio)

For most of the new data modes you probably want --preamble-length 1 or 2 as the frames are long and sync very easily.

**Comment by xssfox** [comment]
sometimes rx audio seems to get stuck - not sure.

**Comment by xssfox** [comment]
I think I want to rethink how this works. 700d worked because we knew that we would always get a frame and if we missed one we could work that out. this isn't really the case with the new data modes. The other part is that these new modes have much higher payload bits - we should make use of that. it'd be nice not to waste a byte on a frame counter but it's probably the easiest way to get something functional. We can let freedv handle the CRC. for the smallest mode that would mean that a payload size of 55 bytes per frame.

Freedvtnc currently doesn't support any sort of reverse ack system (I don't think it's really suitable as most KISS TNCs don't really do this I think?) - it does however mean we have no way of doing link management link lowering the data rate. We should probably open 3 modems however for C1,3 and 4 so the client can change between modes.

This new system would only be suitable for these modes.

At the same time I think I want to switch to using cffi for binding the library.

freedata suggests that freedv preamble generation doesn't work so maybe we need to think about that - maybe we preamble with some metadata such as length and parity so we can loose a frame and still decode.

I think it might also be possible to get smarter with pyaudio and doing async things

I might spin this into its own new project.

**Comment by xssfox** [comment]
@rafael2k @M0LTE I've just released an early revision of freedvtnc2 that uses the new data modes : https://github.com/xssfox/freedvtnc2

**Comment by rafael2k** [comment]
Yay, this is really cool! Thanks @xssfox !

**Comment by xssfox** [comment]
Closing this in favour of tracking bugs in : http://github.com/xssfox/freedvtnc2
